channels:
- conda-forge
dependencies:
- nbsphinx
- dill
- furo
- future
- gitpython
- h5io
- h5py
- myst-parser
- numpy
- pandas
- pathlib2
- pint
- psutil
- pyfileindex
- pysqa
- pytables
- sphinx-copybutton
- sphinx-design
- sphinx-inline-tabs
- sphinx_rtd_theme
- sqlalchemy
- tqdm
- traitlets
